### ISSUE TITLE
Fields which refer to a rule Id is sometimes named 'ruleId' and other times 'id'.

### ISSUE THREAD

**Issue by rtaket** [Microsoft/sarif-sdk#83] opened 2016-01-22 18:19 UTC
In the results node, a rule is identified by the “ruleId” field. In the ruleInfo node a rule is identified by the “id” field. It would be nice if these were named the same since they refer to the same value.

**Comment by michaelcfanning** [comment] 2016-04-28 22:55
we call a the id in a result a ruleId because it is a link to the rules object. similarly, we call the formatted message a formattedRuleMessage to indicate that the supporting information is in the rules object. elsewhere in the standard, an identifier may be rendered as 'id' when it isn't referencing external content. 

propose to close this by design. @lgolding ?

**Comment by lgolding** [comment] 2016-04-28 22:58
Yes. My preference is to call a thing's id "id", and if the thing needs somebody else's id, they qualify it like "fooId".

**Closed by lgolding** 2016-04-28 22:58 UTC
Labels: wontfix
